export const TODO_FORM_UPDATE = 'TODO_FORM_UPDATE';
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';

export const TODOS_FETCH_SUCCESS = 'TODOS_FETCH_SUCCESS';
export const TODOS_FETCH_ERROR = 'TODOS_FETCH_ERROR';
export const TODOS_FETCH_REQUEST = 'TODOS_FETCH_REQUEST';

export const TODOS_ADD_REQUEST = 'TODOS_ADD_REQUEST';
export const TODOS_ADD_SUCCESS = 'TODOS_ADD_SUCCESS';
export const TODOS_ADD_ERROR = 'TODOS_ADD_ERROR';

export const TODOS_REMOVE_REQUEST = 'TODOS_REMOVE_REQUEST';
export const TODOS_REMOVE_SUCCESS = 'TODOS_REMOVE_SUCCESS';
export const TODOS_REMOVE_ERROR = 'TODOS_REMOVE_ERROR';

export const AUTH_STATUS_CHANGE = 'AUTH_STATUS_CHANGE';
export const AUTH_EMAIL_REQUEST = 'AUTH_EMAIL_REQUEST';
export const AUTH_EMAIL_ERROR = 'AUTH_EMAIL_ERROR';
export const AUTH_REGISTER_EMAIL_REQUEST = 'AUTH_REGISTER_EMAIL_REQUEST';


export const AUTH_REGISTER_EMAIL = 'AUTH_REGISTER_EMAIL';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
